language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - release20
    - develop21

# build with both gcc and clang to ensure compatibility
compiler:
  - gcc

before_install:
# Get Eluna
 - git submodule init
 - git submodule update
 
script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
  - make -j4
