language: cpp

# use docker in travis
sudo: false

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master
# send notifications to stack as well as email
notifications:
  slack: getmangos:yRgNBSgRQVh8WdfGEbT08Hit

# build on both Linux and OSX
os:
  - linux
#  - osx

# build with both gcc and clang to ensure compatibility
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - clang

before_install:
  - bash .travis.sh
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CC" = "gcc" ] ; then export CC=gcc-4.9 CXX=g++-4.9 ; fi

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../_install -DSOAP=1 -DPLAYERBOTS=1 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/
  - which openssl
  - make -j4
