version: 0.21.{build}

# Branches to build
branches:
  only:
  - master

# Specify platform for MySQL check
platform:
  - Win32
  
# By default, AppVeyor only comes with 64bit MySQL, but 32 bit compiler.
# Download standalone MySQL libraries for compilation.
# Probably not the best solution, but it works for now.
install:
  - ps: |
        if ($env:platform -eq "Win32")
        {
            Invoke-WebRequest "http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.28-win32.zip" -OutFile mysql-5.6.28-win32.zip
            7z e -y mysql-5.6.28-win32.zip mysql-5.6.28-win32/lib -o"C:\Program Files (x86)\MySql\MySQL Server 5.6\lib"
            7z e -y mysql-5.6.28-win32.zip mysql-5.6.28-win32/include -o"C:\Program Files (x86)\MySql\MySQL Server 5.6\include"
        }

# Clone to the specified folder below, and only clone the latest commit without history.
clone_folder: c:\mzero\server

clone_depth: 1

# Enable parallel builds to speed up the compilation process.
build:
  parallel: true

# Initialize submodules.
before_build:
  - git submodule update --init --recursive
 
# Build core.
build_script:
  - cd c:\mzero\server
  - cmake -DCMAKE_INSTALL_PREFIX="c:\mzero\build\bin" -DCMAKE_SIZEOF_VOID_P=8 -DSOAP:BOOL=1 -DPLAYERBOTS:BOOL=1
  - msbuild /m MaNGOS.sln
