name: core-build
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
    
      matrix:
        compiler: [gcc, clang]
        
        include:
          - os: ubuntu-18.04
            name: Ubuntu 18.04 GCC
            compiler: gcc
            
          - os: ubuntu-18.04
            name: Ubuntu 18.04 Clang
            compiler: clang
            
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    env:
      compiler: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Updates
        run: sudo apt-get update -y
       
      - name: Install Required Packages
        run: sudo apt-get install -y git make cmake gcc g++ clang libssl-dev libbz2-dev build-essential default-libmysqlclient-dev libace-6.4.5 libace-dev python

      - name: Check for Submodule Updates
        run: source ./apps/ci/ci-submodule-update.sh
 
      - name: Build Mangos Project
        run: source ./apps/ci/ci-compile.sh
        
  windows-build:
    strategy:
      fail-fast: false
      
    runs-on: windows-2019
    name: Windows Server 2019
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure Windows
        run: choco install --no-progress openssl
        
      - name: Checkout Submodules
        shell: bash
        run: | 
          git submodule init && git submodule update
        
      - name: Build
        shell: bash
        run: |
          mkdir -p build && cd build
          cmake .. -DTOOLS=ON
          cmake --build . --config Release --parallel 4
      
      - name: Copy dll files
        shell: bash
        run: |
          cp "/c/mysql-5.7.21-winx64/lib/libmysql.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libcrypto-1_1-x64.dll" "build/bin/Release/"
          cp "/c/Program Files/OpenSSL-Win64/bin/libssl-1_1-x64.dll" "build/bin/Release/"
